### ISSUE TITLE
Working with relationships ?

### ISSUE THREAD

**Issue by mathieufrh** [dcasia/batch-edit-toolbar#3]
Hello,

First, thank you for this package and all your other Laravel Nova packages. I am very grateful for your work and for sharing it. These packages provide some very useful features that Nova lacks.

I notice that this package isn't working with related fields, or maybe I just don't know how to use it yet. Is it possible to display a dropdown for a belongsTo relationship ?

**Comment by milewski** [comment]
Can you give me a sample code I can easily copy/paste so I can better understand the issue?

**Comment by mathieufrh** [comment]
Nope; never mind, I just find out that I was using a text field to "supercharge" the field display. It definitely works like a charm. Thank you anyway for the blazing fast answer :-)
